package mingyangzheng.util;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.safety.Whitelist;
import org.jsoup.select.Elements;

/**
 * use jsoup to parse website and remove tags
 * firstly, we only retain the contents in the <p> tag hat do not contain <option> tag in it. Then we replace all the tags in <p> with white space. Next, we only retain number, English character, Punctuation and white space for annotation.
 Then we remove Superscript like "[2]", because this will prevent the Stanford CoreNLP software suite from split sentences correctly. Finaly, we remove "&nbsp;" "&amp;" generated by Jsoup.
 */
public class WebPageParser {
    public static String parseByURL(String url) {
        Document doc = null;
        String text = "";
        try {
            doc = Jsoup.connect(url).get();
            //Elements elements = doc.select("p");
            Elements elements = doc.select("p:not(:has(option))");
            String html = elements.html();
//
            text = Jsoup.clean(html, new Whitelist());
            text = text.replaceAll("[^0-9a-zA-Z\\p{Punct}]+"," ");
            text = text.replaceAll("\\[\\w*\\]","");
            text = text.replaceAll("&nbsp;"," ");
            text = text.replaceAll("&amp;"," ");
//
        } catch (Exception e) {
            System.out.println("cannot connect to this website. Continue to next page");
        }
        return text;
    }
}
